language: go


go:
  - 1.19

stages:
  - Tests
  - Build
  - Plan

jobs:
  include:
    - stage: Tests
      script: 
        - go test --cover -v
    - stage: Build
      script:
        - go mod download
        - go build -v -o get-ninjas-api
    - name: Build And Push Image
      script:
        - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
        - docker build --tag "$DOCKERHUB_USER/get-ninjas-api" .
        - docker push "$DOCKERHUB_USER/get-ninjas-api:latest"
      include:
    - stage: Plan
      env:
        - tf_version=1.1.4 
      script:
        - cd terraform
        - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        - unzip terraform_"$tf_version"_linux_amd64.zip
        - sudo mv terraform /usr/local/bin/
        - rm terraform_"$tf_version"_linux_amd64.zip
        - terraform init
        - terraform plan
        #- terraform destroy -auto-approve

