language: go

go:
  - 1.19

stages:
  - Build
  - Tests
  - Deploy

jobs:
  include:
    - stage: Build
      script:
        - go mod download
        - go build -v -o get-ninjas-api
    - name: Build Image
      script:
        - docker build --tag get-ninjas-api .
    - stage: Tests
      script: 
        - go test --cover -v
