language: go

go:
  - 1.19

stages:
  - Build
  - Tests
  - Deploy

jobs:
  include:
    - stage: Run Tests
      script: 
        - go test --cover -v
    - stage: Build App
      script:
        - go mod download
        - go build -v -o get-ninjas-api
    - name: Build And Push Image
      script:
        - echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
        - docker build --tag get-ninjas-api .
        - docker push "$DOCKERHUB_USER/get-ninjas-api:latest"

