language: go

go:
  - 1.19

stages:
  - Build
  - Tests
  - Deploy

jobs:
  include:
    - stage: Build
      script:
        - go mod init get-ninjas-api 
        - go mod tidy
        - go build -o get-ninjas-api
    - stage: Tests
      script: 
        - go test
